### ISSUE TITLE
Please remove the id label.

### ISSUE THREAD

**Issue by baryluk** [dmitry-ee/time_exporter#1]
```
time_chrony_sources_peer_auth_possible{addr="185.120.22.14",id="5"} 0
time_chrony_sources_peer_offset{addr="185.120.22.14",id="5"} 0.0013166479766368866
...
```

The `addr` is enough. The issue with `id` is that they can change on deamon restart, especially if one uses NTP dns pool instead of a set of fixed addresses, and even they can change dynamically for various reasons. That just will blow number of metrics, and provide no value in monitoring, aggregation, alerting or correlating things. In fact for aggregations, it is useless, and rather a hindrance than a feature, and basically need to be removed by relabeling in prometheus scrape config.

Same for ntpd metrics.

**Comment by dmitry-ee** [comment]
Hi!
Thanks for pointing on the issue.
I'm aware of consequences of having constantly changing labels.

Initially I had a concern about this label exactly, but left it like this.

Will fix it once I get my laptop

**Comment by dmitry-ee** [comment]
@baryluk fixed in [v0.0.3](https://github.com/dmitry-ee/time_exporter/releases/tag/0.0.3), please check

```code
time_chrony_sources_peer_auth_possible{addr="129.250.35.250"} 0
time_chrony_sources_peer_auth_possible{addr="2001:67c:1560:8003::c7"} 0
time_chrony_sources_peer_auth_possible{addr="2001:67c:1560:8003::c8"} 0
time_chrony_sources_peer_auth_possible{addr="2a07:301:8000::5"} 0
time_chrony_sources_peer_auth_possible{addr="85.236.36.4"} 0
time_chrony_sources_peer_auth_possible{addr="91.189.89.198"} 0
time_chrony_sources_peer_auth_possible{addr="91.189.91.157"} 0
time_chrony_sources_peer_auth_possible{addr="94.130.184.193"} 0
time_chrony_sources_peer_offset{addr="129.250.35.250"} -0.0005766269750893116
time_chrony_sources_peer_offset{addr="2001:67c:1560:8003::c7"} 0.0014476289507001638
time_chrony_sources_peer_offset{addr="2001:67c:1560:8003::c8"} 0.0017296000150963664
time_chrony_sources_peer_offset{addr="2a07:301:8000::5"} -0.0031461019534617662
time_chrony_sources_peer_offset{addr="85.236.36.4"} 0.003937650937587023
time_chrony_sources_peer_offset{addr="91.189.89.198"} 0.001862596021965146
time_chrony_sources_peer_offset{addr="91.189.91.157"} 0.00036735000321641564
time_chrony_sources_peer_offset{addr="94.130.184.193"} -0.0010376119753345847
```

**Comment by dmitry-ee** [comment]
Closed with no response from the author @baryluk

**Comment by baryluk** [comment]
@dmitry-ee Hi, sorry for the late response.

Unfortunately, I am getting errors when testing this now:

```
level=debug ts=2021-11-23T18:13:47.475Z caller=chrony.go:226 collector=chrony msg="request to chronyd failed" err="failed to get 'tracking' response: read unixgram @->/run/chrony/chronyd.sock: i/o timeout"
level=debug ts=2021-11-23T18:13:47.475Z caller=collector.go:156 msg="collector returned no data" name=chrony duration_seconds=5.001593434 err="collector returned no data"
```

If I call `chronyc tracking`, it shows me status without any errors (both when connecting over socket `/run/chrony/chronyd.sock` and using UDP `127.0.0.1:323`).

I am using chrony 4.1-3 from Fedora 35.

**Comment by dmitry-ee** [comment]
@baryluk i'm still trying to resolve issue when connecting via socket, but connection through UDP must work fine.
Have you tried to set flag `--collector.chrony.address=127.0.0.1:323`?
And it worth to check `chrony.conf`, on my dev machine i'm using this part of config
```
allow all
cmdallow all
bindcmdaddress 0.0.0.0
bindcmdaddress ::
bindaddress 0.0.0.0
bindaddress ::
bindacqaddress 0.0.0.0
bindacqaddress ::
cmdport 323
```

**Comment by baryluk** [comment]
@dmitry-ee 

Indeed.

Started now with `./time_exporter --collector.chrony.address=127.0.0.1:323`

and it works. :)

Also `id` labels are gone as request.

Thank you!
